package com.ams.enums;

public enum NotificationType {
    ORGANIZATION_INVITATION,
    ORGANIZATION_INVITATION_ACCEPTED,
    ORGANIZATION_INVITATION_REJECTED,

    ORGANIZATION_JOIN_REQUEST,
    ORGANIZATION_JOIN_REQUEST_ACCEPTED,
    ORGANIZATION_JOIN_REQUEST_REJECTED,
}
