package com.ams.enums;

public enum OrganizationActivityType {
    ORGANIZATION_CREATED,
    ORGANIZATION_UPDATED,

    MEMBER_JOINED,
    MEMBER_LEFT,

    MEMBER_INVITED,
    INVITATION_ACCEPTED,
    INVITATION_REJECTED,

    JOIN_REQUEST_SENT,
    JOIN_REQUEST_ACCEPTED,
    JOIN_REQUEST_REJECTED;
}
